
insert into S1
select * from S1_stg where True
ON conflict(phone) DO UPDATE SET 
accepts_financial_aid=excluded.accepts_financial_aid,
ages_served=excluded.ages_served,
capacity=excluded.capacity,
certificate_expiration_date=excluded.certificate_expiration_date,
city=excluded.city,
address1=excluded.address1,
address2=excluded.address2,
company=excluded.company,
phone=excluded.phone,
phone2=excluded.phone2,
county=excluded.county,
curriculum_type=excluded.curriculum_type,
email=excluded.email,
first_name=excluded.first_name,
language=excluded.language,
last_name=excluded.last_name,
license_status=excluded.license_status,
license_issued=excluded.license_issued,
license_number=excluded.license_number,
license_renewed=excluded.license_renewed,
license_type=excluded.license_type,
licensee_name=excluded.licensee_name,
max_age=excluded.max_age,
min_age=excluded.min_age,
operator=excluded.operator,
provider_id=excluded.provider_id,
schedule=excluded.schedule,
state=excluded.state,
title=excluded.title,
website_address=excluded.website_address,
zip=excluded.zip,
facility_type=excluded.facility_type,
source=excluded.source,
source_file=excluded.source_file,
_update_ts=current_timestamp
;