
CREATE TABLE "S1" (
  "accepts_financial_aid" TEXT,
  "ages_served" TEXT,
  "capacity" TEXT,
  "certificate_expiration_date" DATE,
  "city" TEXT,
  "address1" TEXT,
  "address2" TEXT,
  "company" TEXT,
  "phone" TEXT,
  "phone2" TEXT,
  "county" TEXT,
  "curriculum_type" TEXT,
  "email" TEXT,
  "first_name" TEXT,
  "language" TEXT,
  "last_name" TEXT,
  "license_status" TEXT,
  "license_issued" DATE,
  "license_number" TEXT,
  "license_renewed" TEXT,
  "license_type" TEXT,
  "licensee_name" TEXT,
  "max_age" TEXT,
  "min_age" TEXT,
  "operator" TEXT,
  "provider_id" TEXT,
  "schedule" TEXT,
  "state" TEXT,
  "title" TEXT,
  "website_address" TEXT,
  "zip" TEXT,
  "facility_type" TEXT,
  "source"  TEXT,
  "source_file" TEXT,
  "_create_ts" TIMESTAMP,
  "_update_ts" TIMESTAMP,
  
  PRIMARY KEY (phone)
);